name: Run Remote Container Tests on EC2

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH to EC2 and run tests inside container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          
          script: |
            CONTAINER_ID=$(docker ps --filter "name=python-app" --format "{{.ID}}")
            if [ -z "$CONTAINER_ID" ]; then
              echo "Contenedor python-app no se está ejecutando"
              exit 1
            fi
            echo "Contenedor ID: $CONTAINER_ID"
            # Ejecutar las pruebas dentro de la carpeta correcta
            docker exec -w /code/app $CONTAINER_ID pytest tests/
