name: Deploy App
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - develop
  #     - 'feature/**'
  # pull_request:
  #   branches:
  #     - main
  #     - develop
jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Connect and deploy app container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/final-project-devOps

              git pull
              docker-compose pull app
              docker-compose up -d app
