name: Build and Push Docker Image to Nexus

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  workflow_dispatch:

jobs:
  docker-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Nexus Docker Registry
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: echo "$NEXUS_PASSWORD" | docker login ${{ secrets.NEXUS_URL }} -u $NEXUS_USERNAME --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.NEXUS_URL }}/docker-repo/fastapi-project-app:latest ./app

      - name: List Docker images (debug)
        run: docker images

      - name: Push Docker image to Nexus
        run: |
          docker push ${{ secrets.NEXUS_URL }}/docker-repo/fastapi-project-app:latest
