name: Build and Push Docker Image to Nexus

on:
  push:
    branches:
      - main
      - develop
      # - 'feature/**'
  workflow_dispatch:

jobs:
  build-and-push-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build y push en EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/final-project-devOps
            git pull
            docker login ${{ secrets.NEXUS_URL }} -u ${{ secrets.NEXUS_USERNAME }} -p ${{ secrets.NEXUS_PASSWORD }}
            docker build -t ${{ secrets.NEXUS_URL }}/docker-repo/fastapi-project-app:latest ./app
            docker push ${{ secrets.NEXUS_URL }}/docker-repo/fastapi-project-app:latest
